[workspace]
members = ["day*"]
resolver = "3"

[workspace.package]
authors = ["Laurent Pireyn <laurent@pireyn.be>"]
edition = "2024"
license = "Unlicense"
repository = "https://github.com/lpireyn/aoc-rust"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
