[package]
name = "day04"
version = "0.1.0"
authors.workspace = true
description = "Advent of Code 2025, day 4"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
